[theme]
primaryColor="#7B1FA2"         # Viola acceso
backgroundColor="#FFFFFF"      # Sfondo bianco
secondaryBackgroundColor="#F3E5F5"  # Viola molto chiaro per i box
textColor="#2C2C2C"
font="sans serif"
